name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # Ou use 'master' se for sua branch principal
  workflow_dispatch:    # Permite executar o workflow manualmente pela interface do GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      
      - name: Set up Python
        uses: actions/setup-python@main
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask requests markdown Frozen-Flask
      
      - name: Generate static site
        run: |
          python freeze.py
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@main
        with:
          GITHUB_TOKEN: ${{ secrets.token }}
          folder: build  # Diretório de saída do site estático
          branch: gh-pages  # Branch onde o site será publicado